version: '3.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      -  "C://Users//sagar//Downloads//demo(3)//demo//data:/var/lib/mysql"